default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  
development:
  <<: *default
  database: converter_development

test:
  <<: *default
  database: converter_test

production:
  <<: *default
  host:     <%= Rails.application.credentials.db.host %>
  port:     <%= Rails.application.credentials.db.port %>
  username: <%= Rails.application.credentials.db.username %>
  password: <%= Rails.application.credentials.db.password %>
  database: <%= Rails.application.credentials.db.database %>
